#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.12
# from Racc grammer file "".
#

require 'racc/parser.rb'


  require "./lib/lang/comment_lexer.rb"

class CommentParser < Racc::Parser

module_eval(<<'...end comment_parser.y/module_eval...', 'comment_parser.y', 44)

  def parse(code, show_tokens=false)
    @tokens = CommentLexer.new.tokenize(code) # Tokenize the code using our lexer
    puts @tokens.inspect if show_tokens
    do_parse # Kickoff the parsing process
  end

  def next_token
    @tokens.shift
  end
...end comment_parser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
     6,     5,    17,     8,    10,     9,     7,     6,     5,    18,
     8,    13,     9,     7,    14,    15,    16,    19,    20 ]

racc_action_check = [
     0,     0,    10,     0,     1,     0,     0,     2,     2,    13,
     2,     5,     2,     2,     6,     6,     6,    14,    14 ]

racc_action_pointer = [
    -2,     4,     5,   nil,   nil,     5,     8,   nil,   nil,   nil,
     2,   nil,   nil,     5,    10,   nil,   nil,   nil,   nil,   nil,
   nil ]

racc_action_default = [
    -1,   -15,    -2,    -4,    -6,   -15,   -15,   -12,   -13,   -14,
   -15,    -3,    -5,   -15,   -15,   -10,   -11,    21,    -7,    -8,
    -9 ]

racc_goto_table = [
     4,     3,    12,    11,     2,     1 ]

racc_goto_check = [
     4,     3,     4,     3,     2,     1 ]

racc_goto_pointer = [
   nil,     5,     4,     1,     0 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  0, 10, :_reduce_1,
  1, 10, :_reduce_2,
  2, 11, :_reduce_3,
  1, 11, :_reduce_4,
  2, 11, :_reduce_5,
  1, 11, :_reduce_6,
  3, 12, :_reduce_7,
  3, 12, :_reduce_8,
  3, 12, :_reduce_9,
  2, 12, :_reduce_10,
  2, 12, :_reduce_11,
  1, 13, :_reduce_none,
  1, 13, :_reduce_none,
  1, 13, :_reduce_none ]

racc_reduce_n = 15

racc_shift_n = 21

racc_token_table = {
  false => 0,
  :error => 1,
  :COMMENT_LINE => 2,
  :COMMENT_START => 3,
  :COMMENT_END => 4,
  :IDENTIFIER => 5,
  :COMMENT => 6,
  :NEW_LINE => 7,
  :EOF => 8 }

racc_nt_base = 9

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "COMMENT_LINE",
  "COMMENT_START",
  "COMMENT_END",
  "IDENTIFIER",
  "COMMENT",
  "NEW_LINE",
  "EOF",
  "$start",
  "program",
  "expressions",
  "comment",
  "non_comment" ]

Racc_debug_parser = true

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'comment_parser.y', 16)
  def _reduce_1(val, _values, result)
     result = [] 
    result
  end
.,.,

module_eval(<<'.,.,', 'comment_parser.y', 17)
  def _reduce_2(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'comment_parser.y', 20)
  def _reduce_3(val, _values, result)
     result = val[0] << val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'comment_parser.y', 21)
  def _reduce_4(val, _values, result)
     result = val 
    result
  end
.,.,

module_eval(<<'.,.,', 'comment_parser.y', 22)
  def _reduce_5(val, _values, result)
     result = val[0] + "\n" 
    result
  end
.,.,

module_eval(<<'.,.,', 'comment_parser.y', 23)
  def _reduce_6(val, _values, result)
     result = "\n" 
    result
  end
.,.,

module_eval(<<'.,.,', 'comment_parser.y', 26)
  def _reduce_7(val, _values, result)
     result = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'comment_parser.y', 27)
  def _reduce_8(val, _values, result)
     result = val[1] + "\n" 
    result
  end
.,.,

module_eval(<<'.,.,', 'comment_parser.y', 28)
  def _reduce_9(val, _values, result)
     result = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'comment_parser.y', 29)
  def _reduce_10(val, _values, result)
     result = "" 
    result
  end
.,.,

module_eval(<<'.,.,', 'comment_parser.y', 30)
  def _reduce_11(val, _values, result)
     result = "" 
    result
  end
.,.,

# reduce 12 omitted

# reduce 13 omitted

# reduce 14 omitted

def _reduce_none(val, _values, result)
  val[0]
end

end   # class CommentParser
